SELECT PRODUCT_CATEGORY,
       COUNT(CASE WHEN REGION = 'NORTH' THEN 1 END)                                               AS NORTH_SALES_COUNT,
       SUM(CASE WHEN REGION = 'NORTH' THEN QUANTITY_SOLD * UNIT_PRICE * (1 - DISCOUNT / 100) END) AS NORTH_TOTAL_SALES,

       COUNT(CASE WHEN REGION = 'SOUTH' THEN 1 END)                                               AS SOUTH_SALES_COUNT,
       SUM(CASE WHEN REGION = 'SOUTH' THEN QUANTITY_SOLD * UNIT_PRICE * (1 - DISCOUNT / 100) END) AS SOUTH_TOTAL_SALES,

       COUNT(CASE WHEN REGION = 'EAST' THEN 1 END)                                                AS EAST_SALES_COUNT,
       SUM(CASE WHEN REGION = 'EAST' THEN QUANTITY_SOLD * UNIT_PRICE * (1 - DISCOUNT / 100) END)  AS EAST_TOTAL_SALES,

       COUNT(CASE WHEN REGION = 'WEST' THEN 1 END)                                                AS WEST_SALES_COUNT,
       SUM(CASE WHEN REGION = 'WEST' THEN QUANTITY_SOLD * UNIT_PRICE * (1 - DISCOUNT / 100) END)  AS WEST_TOTAL_SALES,

       COUNT(*)                                                                                   AS TOTAL_TRANSACTIONS,
       SUM(QUANTITY_SOLD * UNIT_PRICE * (1 - DISCOUNT / 100))                                     AS OVERALL_TOTAL_SALES
FROM SALES
GROUP BY PRODUCT_CATEGORY
ORDER BY OVERALL_TOTAL_SALES DESC;

SELECT
    SALES_PERSON,

    COUNT(CASE WHEN PRODUCT_CATEGORY = 'ELECTRONICS' THEN 1 END) AS ELECTRONICS_SALES,
    COUNT(CASE WHEN PRODUCT_CATEGORY = 'CLOTHING' THEN 1 END)    AS CLOTHING_SALES,
    COUNT(CASE WHEN PRODUCT_CATEGORY = 'FURNITURE' THEN 1 END)   AS FURNITURE_SALES,

    ROUND(SUM(CASE WHEN PRODUCT_CATEGORY = 'ELECTRONICS' THEN QUANTITY_SOLD * UNIT_PRICE * (1 - DISCOUNT/100) END), 2) AS ELECTRONICS_REVENUE,
    ROUND(SUM(CASE WHEN PRODUCT_CATEGORY = 'CLOTHING' THEN QUANTITY_SOLD * UNIT_PRICE * (1 - DISCOUNT/100) END), 2)    AS CLOTHING_REVENUE,
    ROUND(SUM(CASE WHEN PRODUCT_CATEGORY = 'FURNITURE' THEN QUANTITY_SOLD * UNIT_PRICE * (1 - DISCOUNT/100) END), 2)   AS FURNITURE_REVENUE,

    ROUND(SUM(QUANTITY_SOLD * UNIT_PRICE * (1 - DISCOUNT/100)), 2) AS TOTAL_REVENUE
FROM SALES
GROUP BY SALES_PERSON
ORDER BY TOTAL_REVENUE DESC ;