-- CTE : Employees with salary above average
WITH AVERAGE_SALARY AS (
    SELECT
        AVG(SALARY) AVG_SALARY
    FROM EMPLOYEES
)
SELECT
    CONCAT(E.FIRST_NAME, ' ', E.LAST_NAME)       FULL_NAME,
    E.SALARY,
    ROUND(E.SALARY - AVS.AVG_SALARY, 2) AS DIFFERENCE,
    ROUND((E.SALARY / AVS.AVG_SALARY) * 100, 2) AS PERCENT_OF_AVG
FROM EMPLOYEES E
         CROSS JOIN AVERAGE_SALARY AVS
WHERE E.SALARY > AVS.AVG_SALARY
ORDER BY E.SALARY DESC;

-- Without CTE (Standard SQL)
SELECT
    CONCAT(E.FIRST_NAME, ' ', E.LAST_NAME) AS FULL_NAME,
    E.SALARY,
    ROUND(E.SALARY - (SELECT AVG(SALARY) FROM EMPLOYEES), 2) AS DIFFERENCE, -- subquery 1
    ROUND(E.SALARY / (SELECT AVG(SALARY) FROM EMPLOYEES) * 100, 2) AS PERCENT_OF_AVG -- subquery 2
FROM EMPLOYEES E
WHERE E.SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES) -- subquery 3
ORDER BY E.SALARY DESC;

-- CTE : Department statistics
WITH DEPT_STATS AS (
    SELECT
        DEPARTMENT_ID,
        ROUND(AVG(SALARY), 2) AS AVG_DEPT_SALARY,
        ROUND(MAX(SALARY), 2)  AS MAX_DEPT_SALARY,
        ROUND(MIN(SALARY), 2) AS MIN_DEPT_SALARY,
        COUNT(*) AS EMPLOYEE_COUNT
    FROM EMPLOYEES
    GROUP BY DEPARTMENT_ID
)
SELECT
    D.DEPARTMENT_NAME,
    CONCAT(E.FIRST_NAME, ' ', E.LAST_NAME) AS EMPLOYEE_NAME,
    E.SALARY,
    DS.AVG_DEPT_SALARY,
    DS.MAX_DEPT_SALARY,
    DS.MIN_DEPT_SALARY,
    DS.EMPLOYEE_COUNT,
    ROUND((E.SALARY / DS.AVG_DEPT_SALARY) * 100, 2) AS PERCENT_OF_AVG
FROM EMPLOYEES E
         JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
         JOIN DEPT_STATS DS ON E.DEPARTMENT_ID = DS.DEPARTMENT_ID
ORDER BY D.DEPARTMENT_NAME, E.SALARY DESC;

-- Without CTE (Standard SQL) with 5 subqueries
SELECT
    D.DEPARTMENT_NAME,
    CONCAT(E.FIRST_NAME, ' ', E.LAST_NAME) AS EMPLOYEE_NAME,
    E.SALARY,
    (SELECT AVG(SALARY) FROM EMPLOYEES E2 WHERE E2.DEPARTMENT_ID = E.DEPARTMENT_ID) AS AVG_DEPT_SALARY,
    (SELECT MAX(SALARY) FROM EMPLOYEES E2 WHERE E2.DEPARTMENT_ID = E.DEPARTMENT_ID) AS MAX_DEPT_SALARY,
    (SELECT MIN(SALARY) FROM EMPLOYEES E2 WHERE E2.DEPARTMENT_ID = E.DEPARTMENT_ID) AS MIN_DEPT_SALARY,
    (SELECT COUNT(*) FROM EMPLOYEES E2 WHERE E2.DEPARTMENT_ID = E.DEPARTMENT_ID) AS EMPLOYEE_COUNT,
    ROUND((E.SALARY / (SELECT AVG(SALARY) FROM EMPLOYEES E2 WHERE E2.DEPARTMENT_ID = E.DEPARTMENT_ID)) * 100, 2) AS PERCENT_OF_AVG
FROM EMPLOYEES E
         JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
ORDER BY D.DEPARTMENT_NAME, E.SALARY DESC;


-- Recursive CTE : Number sequence
WITH RECURSIVE NUMBER_SEQUENCE AS (
    -- ANCHOR MEMBER: Start with 1
    SELECT 1 AS NUMBER_VALUE
    UNION ALL
    -- RECURSIVE MEMBER: Add 1 each time
    SELECT NUMBER_VALUE + 1
    FROM NUMBER_SEQUENCE
    WHERE NUMBER_VALUE < 10
)
SELECT * FROM NUMBER_SEQUENCE;


-- Without CTE (Standard SQL - using existing table or UNION ALL)
SELECT 1 AS NUMBER_VALUE UNION ALL
SELECT 2 UNION ALL
SELECT 3 UNION ALL
SELECT 4 UNION ALL
SELECT 5 UNION ALL
SELECT 6 UNION ALL
SELECT 7 UNION ALL
SELECT 8 UNION ALL
SELECT 9 UNION ALL
SELECT 10;


-- CTE Example: Employee hierarchy
WITH RECURSIVE EMPLOYEE_HIERARCHY AS (
    -- ANCHOR MEMBER: Top level managers (no manager)
    SELECT
        EMPLOYEE_ID,
        FIRST_NAME,
        LAST_NAME,
        MANAGER_ID,
        1 AS HIERARCHY_LEVEL,
        CONCAT(FIRST_NAME, ' ', LAST_NAME) AS PATH
    FROM EMPLOYEES
    WHERE MANAGER_ID IS NULL

    UNION ALL

    -- RECURSIVE MEMBER: Employees with managers
    SELECT
        E.EMPLOYEE_ID,
        E.FIRST_NAME,
        E.LAST_NAME,
        E.MANAGER_ID,
        H.HIERARCHY_LEVEL + 1,
        CONCAT(H.PATH, ' -> ', E.FIRST_NAME, ' ', E.LAST_NAME)
    FROM EMPLOYEES E
             INNER JOIN EMPLOYEE_HIERARCHY H ON E.MANAGER_ID = H.EMPLOYEE_ID
)
SELECT
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    HIERARCHY_LEVEL,
    PATH
FROM EMPLOYEE_HIERARCHY
ORDER BY PATH;


-- Without CTE (Standard SQL - using self-joins for fixed levels)
-- Note: This only works for a fixed number of levels
SELECT
    E1.EMPLOYEE_ID,
    E1.FIRST_NAME,
    E1.LAST_NAME,
    CASE
        WHEN E1.MANAGER_ID IS NULL THEN 1
        WHEN E2.MANAGER_ID IS NULL THEN 2
        WHEN E3.MANAGER_ID IS NULL THEN 3
        ELSE 4
        END AS HIERARCHY_LEVEL,
    CONCAT(
            COALESCE(CONCAT(E3.FIRST_NAME, ' ', E3.LAST_NAME, ' -> '), ''),
            COALESCE(CONCAT(E2.FIRST_NAME, ' ', E2.LAST_NAME, ' -> '), ''),
            COALESCE(CONCAT(E1.FIRST_NAME, ' ', E1.LAST_NAME), '')
    ) AS PATH
FROM EMPLOYEES E1
         LEFT JOIN EMPLOYEES E2 ON E1.MANAGER_ID = E2.EMPLOYEE_ID
         LEFT JOIN EMPLOYEES E3 ON E2.MANAGER_ID = E3.EMPLOYEE_ID
ORDER BY
    COALESCE(E3.EMPLOYEE_ID, E2.EMPLOYEE_ID, E1.EMPLOYEE_ID),
    E2.EMPLOYEE_ID,
    E1.EMPLOYEE_ID;