-- CTE : Employees with salary above average
WITH AVERAGE_SALARY AS (
    SELECT
        AVG(SALARY) AVG_SALARY
    FROM EMPLOYEES
)
SELECT
    CONCAT(E.FIRST_NAME, ' ', E.LAST_NAME)       FULL_NAME,
    E.SALARY,
    ROUND(E.SALARY - AVS.AVG_SALARY, 2) AS DIFFERENCE,
    ROUND((E.SALARY / AVS.AVG_SALARY) * 100, 2) AS PERCENT_OF_AVG
FROM EMPLOYEES E
         CROSS JOIN AVERAGE_SALARY AVS
WHERE E.SALARY > AVS.AVG_SALARY
ORDER BY E.SALARY DESC;

-- Without CTE (Standard SQL)
SELECT
    CONCAT(E.FIRST_NAME, ' ', E.LAST_NAME) AS FULL_NAME,
    E.SALARY,
    ROUND(E.SALARY - (SELECT AVG(SALARY) FROM EMPLOYEES), 2) AS DIFFERENCE, -- subquery 1
    ROUND(E.SALARY / (SELECT AVG(SALARY) FROM EMPLOYEES) * 100, 2) AS PERCENT_OF_AVG -- subquery 2
FROM EMPLOYEES E
WHERE E.SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES) -- subquery 3
ORDER BY E.SALARY DESC;

-- CTE : Department statistics
WITH DEPT_STATS AS (
    SELECT
        DEPARTMENT_ID,
        ROUND(AVG(SALARY), 2) AS AVG_DEPT_SALARY,
        ROUND(MAX(SALARY), 2)  AS MAX_DEPT_SALARY,
        ROUND(MIN(SALARY), 2) AS MIN_DEPT_SALARY,
        COUNT(*) AS EMPLOYEE_COUNT
    FROM EMPLOYEES
    GROUP BY DEPARTMENT_ID
)
SELECT
    D.DEPARTMENT_NAME,
    CONCAT(E.FIRST_NAME, ' ', E.LAST_NAME) AS EMPLOYEE_NAME,
    E.SALARY,
    DS.AVG_DEPT_SALARY,
    DS.MAX_DEPT_SALARY,
    DS.MIN_DEPT_SALARY,
    DS.EMPLOYEE_COUNT,
    ROUND((E.SALARY / DS.AVG_DEPT_SALARY) * 100, 2) AS PERCENT_OF_AVG
FROM EMPLOYEES E
         JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
         JOIN DEPT_STATS DS ON E.DEPARTMENT_ID = DS.DEPARTMENT_ID
ORDER BY D.DEPARTMENT_NAME, E.SALARY DESC;

-- Without CTE (Standard SQL) with 5 subqueries
SELECT
    D.DEPARTMENT_NAME,
    CONCAT(E.FIRST_NAME, ' ', E.LAST_NAME) AS EMPLOYEE_NAME,
    E.SALARY,
    (SELECT AVG(SALARY) FROM EMPLOYEES E2 WHERE E2.DEPARTMENT_ID = E.DEPARTMENT_ID) AS AVG_DEPT_SALARY,
    (SELECT MAX(SALARY) FROM EMPLOYEES E2 WHERE E2.DEPARTMENT_ID = E.DEPARTMENT_ID) AS MAX_DEPT_SALARY,
    (SELECT MIN(SALARY) FROM EMPLOYEES E2 WHERE E2.DEPARTMENT_ID = E.DEPARTMENT_ID) AS MIN_DEPT_SALARY,
    (SELECT COUNT(*) FROM EMPLOYEES E2 WHERE E2.DEPARTMENT_ID = E.DEPARTMENT_ID) AS EMPLOYEE_COUNT,
    ROUND((E.SALARY / (SELECT AVG(SALARY) FROM EMPLOYEES E2 WHERE E2.DEPARTMENT_ID = E.DEPARTMENT_ID)) * 100, 2) AS PERCENT_OF_AVG
FROM EMPLOYEES E
         JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
ORDER BY D.DEPARTMENT_NAME, E.SALARY DESC;