-- CTE : Employees with salary above average
WITH AVERAGE_SALARY AS (
    SELECT
        AVG(SALARY) AVG_SALARY
    FROM EMPLOYEES
)
SELECT
    CONCAT(E.FIRST_NAME, ' ', E.LAST_NAME)       FULL_NAME,
    E.SALARY,
    ROUND(E.SALARY - AVS.AVG_SALARY, 2) AS DIFFERENCE,
    ROUND((E.SALARY / AVS.AVG_SALARY) * 100, 2) AS PERCENT_OF_AVG
FROM EMPLOYEES E
         CROSS JOIN AVERAGE_SALARY AVS
WHERE E.SALARY > AVS.AVG_SALARY
ORDER BY E.SALARY DESC;

-- Without CTE (Standard SQL)
SELECT
    CONCAT(E.FIRST_NAME, ' ', E.LAST_NAME) AS FULL_NAME,
    E.SALARY,
    ROUND(E.SALARY - (SELECT AVG(SALARY) FROM EMPLOYEES), 2) AS DIFFERENCE, -- subquery 1
    ROUND(E.SALARY / (SELECT AVG(SALARY) FROM EMPLOYEES) * 100, 2) AS PERCENT_OF_AVG -- subquery 2
FROM EMPLOYEES E
WHERE E.SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES) -- subquery 3
ORDER BY E.SALARY DESC;
