-- Basic LAG() Usage
SELECT SELLER,
       SOLD_AT,
       AMOUNT,
       LAG(AMOUNT) OVER (ORDER BY SOLD_AT) PREVISOUS_AMOUNT
FROM SALES;

-- LAG() with PARTITION BY
SELECT SELLER,
       SOLD_AT,
       AMOUNT,
       LAG(AMOUNT) OVER (
           PARTITION BY SELLER -- GROUP/SPLIT ROW BY SELLER  
           ORDER BY SOLD_AT
           ) PREVISOUS_AMOUNT
FROM SALES;



